/** Common public-domain / stock chord progressions for IsoPad Studio. */
window.ISOPAD_PROGRESSIONS = [
  // ── Pop ──────────────────────────────────────────────
  {
    id: "pop-axis",
    name: "I–V–vi–IV",
    aka: "Axis / pop-punk",
    genre: "Pop",
    numerals: "I–V–vi–IV",
    chords: [
      { o: 0, q: "Major" },
      { o: 7, q: "Major" },
      { o: 9, q: "Minor" },
      { o: 5, q: "Major" },
    ],
  },
  {
    id: "pop-sensitive",
    name: "vi–IV–I–V",
    aka: "Pop ballad loop",
    genre: "Pop",
    numerals: "vi–IV–I–V",
    chords: [
      { o: 9, q: "Minor" },
      { o: 5, q: "Major" },
      { o: 0, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "pop-50s",
    name: "I–vi–IV–V",
    aka: "’50s / doo-wop",
    genre: "Pop",
    numerals: "I–vi–IV–V",
    chords: [
      { o: 0, q: "Major" },
      { o: 9, q: "Minor" },
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "pop-iv-v-iii-vi",
    name: "IV–V–iii–vi",
    aka: "Ascending pop turn",
    genre: "Pop",
    numerals: "IV–V–iii–vi",
    chords: [
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
      { o: 4, q: "Minor" },
      { o: 9, q: "Minor" },
    ],
  },
  {
    id: "pop-i-iii-iv-v",
    name: "I–iii–IV–V",
    aka: "Bright pop lift",
    genre: "Pop",
    numerals: "I–iii–IV–V",
    chords: [
      { o: 0, q: "Major" },
      { o: 4, q: "Minor" },
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "pop-i-v-iv-v",
    name: "I–V–IV–V",
    aka: "Simple chorus",
    genre: "Pop",
    numerals: "I–V–IV–V",
    chords: [
      { o: 0, q: "Major" },
      { o: 7, q: "Major" },
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "pop-canon",
    name: "Pachelbel / Canon",
    aka: "I–V–vi–iii–IV–I–IV–V",
    genre: "Pop",
    numerals: "I–V–vi–iii–IV–I–IV–V",
    chords: [
      { o: 0, q: "Major" },
      { o: 7, q: "Major" },
      { o: 9, q: "Minor" },
      { o: 4, q: "Minor" },
      { o: 5, q: "Major" },
      { o: 0, q: "Major" },
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "pop-i-iv-vi-v",
    name: "I–IV–vi–V",
    aka: "Modern worship / pop",
    genre: "Pop",
    numerals: "I–IV–vi–V",
    chords: [
      { o: 0, q: "Major" },
      { o: 5, q: "Major" },
      { o: 9, q: "Minor" },
      { o: 7, q: "Major" },
    ],
  },

  // ── Rock ─────────────────────────────────────────────
  {
    id: "rock-i-bvii-iv",
    name: "I–♭VII–IV",
    aka: "Classic rock anthem",
    genre: "Rock",
    numerals: "I–♭VII–IV",
    chords: [
      { o: 0, q: "Major" },
      { o: 10, q: "Major" },
      { o: 5, q: "Major" },
    ],
  },
  {
    id: "rock-i-iv-bvii-iv",
    name: "I–IV–♭VII–IV",
    aka: "Mixolydian rock",
    genre: "Rock",
    numerals: "I–IV–♭VII–IV",
    chords: [
      { o: 0, q: "Major" },
      { o: 5, q: "Major" },
      { o: 10, q: "Major" },
      { o: 5, q: "Major" },
    ],
  },
  {
    id: "rock-i-v-bvii-iv",
    name: "I–V–♭VII–IV",
    aka: "Stadium rock",
    genre: "Rock",
    numerals: "I–V–♭VII–IV",
    chords: [
      { o: 0, q: "Major" },
      { o: 7, q: "Major" },
      { o: 10, q: "Major" },
      { o: 5, q: "Major" },
    ],
  },
  {
    id: "rock-i-biii-iv",
    name: "I–♭III–IV",
    aka: "Hard rock turn",
    genre: "Rock",
    numerals: "I–♭III–IV",
    chords: [
      { o: 0, q: "Major" },
      { o: 3, q: "Major" },
      { o: 5, q: "Major" },
    ],
  },
  {
    id: "rock-power",
    name: "I5–♭VII5–IV5",
    aka: "Power-chord riff",
    genre: "Rock",
    numerals: "I5–♭VII5–IV5",
    chords: [
      { o: 0, q: "Power chord (5)" },
      { o: 10, q: "Power chord (5)" },
      { o: 5, q: "Power chord (5)" },
    ],
  },
  {
    id: "rock-i-vi-bvii-iv",
    name: "I–vi–♭VII–IV",
    aka: "Alt-rock loop",
    genre: "Rock",
    numerals: "I–vi–♭VII–IV",
    chords: [
      { o: 0, q: "Major" },
      { o: 9, q: "Minor" },
      { o: 10, q: "Major" },
      { o: 5, q: "Major" },
    ],
  },
  {
    id: "rock-sus",
    name: "Isus–I–IV–V",
    aka: "Sus resolution rock",
    genre: "Rock",
    numerals: "Isus4–I–IV–V",
    chords: [
      { o: 0, q: "Sus4" },
      { o: 0, q: "Major" },
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },

  // ── Blues ────────────────────────────────────────────
  {
    id: "blues-12",
    name: "12-Bar Major Blues",
    aka: "I7–IV7–V7 form",
    genre: "Blues",
    numerals: "I7 | I7 | I7 | I7 | IV7 | IV7 | I7 | I7 | V7 | IV7 | I7 | V7",
    chords: [
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "blues-12-quick",
    name: "12-Bar Quick Change",
    aka: "IV in bar 2",
    genre: "Blues",
    numerals: "I7 | IV7 | I7 | I7 | IV7 | IV7 | I7 | I7 | V7 | IV7 | I7 | V7",
    chords: [
      { o: 0, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "blues-12-minor",
    name: "12-Bar Minor Blues",
    aka: "i–iv–V7 minor form",
    genre: "Blues",
    numerals: "i7 | i7 | i7 | i7 | iv7 | iv7 | i7 | i7 | V7 | iv7 | i7 | V7",
    chords: [
      { o: 0, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
      { o: 5, q: "Minor 7" },
      { o: 5, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
      { o: 5, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "blues-8",
    name: "8-Bar Blues",
    aka: "Compact blues form",
    genre: "Blues",
    numerals: "I7 | V7 | IV7 | IV7 | I7 | V7 | I7 | V7",
    chords: [
      { o: 0, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "blues-16",
    name: "16-Bar Blues",
    aka: "Extended I stretch",
    genre: "Blues",
    numerals: "I7×8 | IV7×2 | I7×2 | V7 | IV7 | I7 | V7",
    chords: [
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
      { o: 5, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "blues-shuffle-turn",
    name: "Blues Turnaround",
    aka: "I–VI7–ii–V",
    genre: "Blues",
    numerals: "I7–VI7–ii7–V7",
    chords: [
      { o: 0, q: "Dominant 7" },
      { o: 9, q: "Dominant 7" },
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },

  // ── Jazz ─────────────────────────────────────────────
  {
    id: "jazz-251",
    name: "ii–V–I",
    aka: "Essential jazz cadence",
    genre: "Jazz",
    numerals: "ii7–V7–Imaj7",
    chords: [
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
      { o: 0, q: "Major 7" },
    ],
  },
  {
    id: "jazz-2516",
    name: "ii–V–I–vi",
    aka: "Turnaround loop",
    genre: "Jazz",
    numerals: "ii7–V7–Imaj7–vi7",
    chords: [
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
      { o: 0, q: "Major 7" },
      { o: 9, q: "Minor 7" },
    ],
  },
  {
    id: "jazz-1625",
    name: "I–vi–ii–V",
    aka: "Rhythm changes A",
    genre: "Jazz",
    numerals: "Imaj7–vi7–ii7–V7",
    chords: [
      { o: 0, q: "Major 7" },
      { o: 9, q: "Minor 7" },
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "jazz-3625",
    name: "iii–vi–ii–V",
    aka: "Descending turnaround",
    genre: "Jazz",
    numerals: "iii7–vi7–ii7–V7",
    chords: [
      { o: 4, q: "Minor 7" },
      { o: 9, q: "Minor 7" },
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "jazz-rhythm-bridge",
    name: "Rhythm Changes Bridge",
    aka: "Circle of dominants",
    genre: "Jazz",
    numerals: "III7–VI7–II7–V7",
    chords: [
      { o: 4, q: "Dominant 7" },
      { o: 9, q: "Dominant 7" },
      { o: 2, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "jazz-minor-251",
    name: "iiø–V–i",
    aka: "Minor ii–V–i",
    genre: "Jazz",
    numerals: "iiø7–V7–i7",
    chords: [
      { o: 2, q: "Half-diminished (m7♭5)" },
      { o: 7, q: "Dominant 7" },
      { o: 0, q: "Minor 7" },
    ],
  },
  {
    id: "jazz-autumn",
    name: "Autumn Leaves Cycle",
    aka: "Major then relative minor",
    genre: "Jazz",
    numerals: "ii7–V7–Imaj7–IV7 | viiø–III7–vi7",
    chords: [
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
      { o: 0, q: "Major 7" },
      { o: 5, q: "Dominant 7" },
      { o: 11, q: "Half-diminished (m7♭5)" },
      { o: 4, q: "Dominant 7" },
      { o: 9, q: "Minor 7" },
    ],
  },
  {
    id: "jazz-so-what",
    name: "So What / Modal Vamp",
    aka: "Dm7 ↔ E♭m7",
    genre: "Jazz",
    numerals: "i7 | i7 | i7 | i7 | ♭ii7 | ♭ii7 | i7 | i7",
    chords: [
      { o: 0, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
      { o: 1, q: "Minor 7" },
      { o: 1, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
      { o: 0, q: "Minor 7" },
    ],
  },
  {
    id: "jazz-a-train",
    name: "I–II7–ii–V",
    aka: "A-Train move",
    genre: "Jazz",
    numerals: "Imaj7–II7–ii7–V7",
    chords: [
      { o: 0, q: "Major 7" },
      { o: 2, q: "Dominant 7" },
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "jazz-bird-blues",
    name: "Bird Blues (simplified)",
    aka: "Jazz blues with ii–V",
    genre: "Jazz",
    numerals: "I7 | vii–III7 | vi–II7 | V7 | …",
    chords: [
      { o: 0, q: "Dominant 7" },
      { o: 11, q: "Minor 7" },
      { o: 4, q: "Dominant 7" },
      { o: 9, q: "Minor 7" },
      { o: 2, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 9, q: "Dominant 7" },
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
      { o: 0, q: "Dominant 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "jazz-coltrane",
    name: "Coltrane Matrix (tonic cycle)",
    aka: "Imaj7–♭IIImaj7–♭VImaj7",
    genre: "Jazz",
    numerals: "Imaj7–♭IIImaj7–♭VImaj7–Imaj7",
    chords: [
      { o: 0, q: "Major 7" },
      { o: 3, q: "Major 7" },
      { o: 8, q: "Major 7" },
      { o: 0, q: "Major 7" },
    ],
  },

  // ── Folk & Country ───────────────────────────────────
  {
    id: "folk-145",
    name: "I–IV–V",
    aka: "Three-chord folk",
    genre: "Folk & Country",
    numerals: "I–IV–V",
    chords: [
      { o: 0, q: "Major" },
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "folk-1564",
    name: "I–V–vi–IV",
    aka: "Folk anthem (same as Axis)",
    genre: "Folk & Country",
    numerals: "I–V–vi–IV",
    chords: [
      { o: 0, q: "Major" },
      { o: 7, q: "Major" },
      { o: 9, q: "Minor" },
      { o: 5, q: "Major" },
    ],
  },
  {
    id: "folk-1645",
    name: "I–vi–IV–V",
    aka: "Country ballad",
    genre: "Folk & Country",
    numerals: "I–vi–IV–V",
    chords: [
      { o: 0, q: "Major" },
      { o: 9, q: "Minor" },
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "country-1565",
    name: "I–V–vi–V",
    aka: "Country waltz feel",
    genre: "Folk & Country",
    numerals: "I–V–vi–V",
    chords: [
      { o: 0, q: "Major" },
      { o: 7, q: "Major" },
      { o: 9, q: "Minor" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "country-1-4-1-5",
    name: "I–IV–I–V",
    aka: "Two-step country",
    genre: "Folk & Country",
    numerals: "I–IV–I–V",
    chords: [
      { o: 0, q: "Major" },
      { o: 5, q: "Major" },
      { o: 0, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "folk-vi-v-iv-v",
    name: "vi–V–IV–V",
    aka: "Minor folk lift",
    genre: "Folk & Country",
    numerals: "vi–V–IV–V",
    chords: [
      { o: 9, q: "Minor" },
      { o: 7, q: "Major" },
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },

  // ── R&B / Soul ───────────────────────────────────────
  {
    id: "rnb-1625",
    name: "I–vi–ii–V",
    aka: "Soul turnaround",
    genre: "R&B / Soul",
    numerals: "Imaj7–vi7–ii7–V7",
    chords: [
      { o: 0, q: "Major 7" },
      { o: 9, q: "Minor 7" },
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "rnb-147",
    name: "Imaj7–iv7–IVmaj7–V7",
    aka: "Minor iv color",
    genre: "R&B / Soul",
    numerals: "Imaj7–iv7–IVmaj7–V7",
    chords: [
      { o: 0, q: "Major 7" },
      { o: 5, q: "Minor 7" },
      { o: 5, q: "Major 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "rnb-circle",
    name: "vi–ii–V–I",
    aka: "Circle-of-fifths soul",
    genre: "R&B / Soul",
    numerals: "vi7–ii7–V7–Imaj7",
    chords: [
      { o: 9, q: "Minor 7" },
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
      { o: 0, q: "Major 7" },
    ],
  },
  {
    id: "rnb-neo",
    name: "i–♭VI–♭VII–i",
    aka: "Neo-soul minor",
    genre: "R&B / Soul",
    numerals: "i7–♭VImaj7–♭VII7–i7",
    chords: [
      { o: 0, q: "Minor 7" },
      { o: 8, q: "Major 7" },
      { o: 10, q: "Dominant 7" },
      { o: 0, q: "Minor 7" },
    ],
  },
  {
    id: "rnb-plagal",
    name: "I–IV–I–IV",
    aka: "Plagal soul vamp",
    genre: "R&B / Soul",
    numerals: "Imaj7–IVmaj7–Imaj7–IVmaj7",
    chords: [
      { o: 0, q: "Major 7" },
      { o: 5, q: "Major 7" },
      { o: 0, q: "Major 7" },
      { o: 5, q: "Major 7" },
    ],
  },

  // ── Latin ────────────────────────────────────────────
  {
    id: "latin-andalusian",
    name: "Andalusian Cadence",
    aka: "i–♭VII–♭VI–V",
    genre: "Latin",
    numerals: "i–♭VII–♭VI–V",
    chords: [
      { o: 0, q: "Minor" },
      { o: 10, q: "Major" },
      { o: 8, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "latin-i-iv-v-iv",
    name: "I–IV–V–IV",
    aka: "Montuno major",
    genre: "Latin",
    numerals: "I–IV–V–IV",
    chords: [
      { o: 0, q: "Major" },
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
      { o: 5, q: "Major" },
    ],
  },
  {
    id: "latin-ii-v-i",
    name: "ii–V–I (Latin)",
    aka: "Salsa / bossa turn",
    genre: "Latin",
    numerals: "ii7–V7–Imaj7",
    chords: [
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
      { o: 0, q: "Major 7" },
    ],
  },
  {
    id: "latin-bossa",
    name: "Bossa Nova Turn",
    aka: "Imaj7–♭IImaj7–ii7–V7",
    genre: "Latin",
    numerals: "Imaj7–♭IImaj7–ii7–V7",
    chords: [
      { o: 0, q: "Major 7" },
      { o: 1, q: "Major 7" },
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
    ],
  },
  {
    id: "latin-clave-minor",
    name: "i–iv–V–i",
    aka: "Minor Latin vamp",
    genre: "Latin",
    numerals: "i–iv–V–i",
    chords: [
      { o: 0, q: "Minor" },
      { o: 5, q: "Minor" },
      { o: 7, q: "Major" },
      { o: 0, q: "Minor" },
    ],
  },

  // ── Metal / Alternative ──────────────────────────────
  {
    id: "metal-aeolian",
    name: "i–♭VII–♭VI–♭VII",
    aka: "Aeolian metal",
    genre: "Metal / Alt",
    numerals: "i–♭VII–♭VI–♭VII",
    chords: [
      { o: 0, q: "Minor" },
      { o: 10, q: "Major" },
      { o: 8, q: "Major" },
      { o: 10, q: "Major" },
    ],
  },
  {
    id: "metal-dorian",
    name: "i–♭VII–IV–i",
    aka: "Dorian rock/metal",
    genre: "Metal / Alt",
    numerals: "i–♭VII–IV–i",
    chords: [
      { o: 0, q: "Minor" },
      { o: 10, q: "Major" },
      { o: 5, q: "Major" },
      { o: 0, q: "Minor" },
    ],
  },
  {
    id: "metal-phrygian",
    name: "i–♭II–i–♭VII",
    aka: "Phrygian metal",
    genre: "Metal / Alt",
    numerals: "i–♭II–i–♭VII",
    chords: [
      { o: 0, q: "Minor" },
      { o: 1, q: "Major" },
      { o: 0, q: "Minor" },
      { o: 10, q: "Major" },
    ],
  },
  {
    id: "metal-i-bvi-bvii",
    name: "i–♭VI–♭VII",
    aka: "Epic minor lift",
    genre: "Metal / Alt",
    numerals: "i–♭VI–♭VII",
    chords: [
      { o: 0, q: "Minor" },
      { o: 8, q: "Major" },
      { o: 10, q: "Major" },
    ],
  },
  {
    id: "alt-i-biii-bvii-iv",
    name: "I–♭III–♭VII–IV",
    aka: "Grunge / alt",
    genre: "Metal / Alt",
    numerals: "I–♭III–♭VII–IV",
    chords: [
      { o: 0, q: "Major" },
      { o: 3, q: "Major" },
      { o: 10, q: "Major" },
      { o: 5, q: "Major" },
    ],
  },

  // ── Gospel / Worship ─────────────────────────────────
  {
    id: "gospel-145",
    name: "I–IV–V–I",
    aka: "Basic gospel cadence",
    genre: "Gospel / Worship",
    numerals: "I–IV–V–I",
    chords: [
      { o: 0, q: "Major" },
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
      { o: 0, q: "Major" },
    ],
  },
  {
    id: "gospel-2-5-1",
    name: "ii–V–I (Gospel)",
    aka: "Church turnaround",
    genre: "Gospel / Worship",
    numerals: "ii7–V7–Imaj7",
    chords: [
      { o: 2, q: "Minor 7" },
      { o: 7, q: "Dominant 7" },
      { o: 0, q: "Major 7" },
    ],
  },
  {
    id: "gospel-walk",
    name: "I–III7–IV–iv",
    aka: "Gospel walkup color",
    genre: "Gospel / Worship",
    numerals: "I–III7–IV–iv",
    chords: [
      { o: 0, q: "Major" },
      { o: 4, q: "Dominant 7" },
      { o: 5, q: "Major" },
      { o: 5, q: "Minor" },
    ],
  },
  {
    id: "worship-1564",
    name: "I–V–vi–IV (Worship)",
    aka: "Modern worship staple",
    genre: "Gospel / Worship",
    numerals: "I–V–vi–IV",
    chords: [
      { o: 0, q: "Major" },
      { o: 7, q: "Major" },
      { o: 9, q: "Minor" },
      { o: 5, q: "Major" },
    ],
  },
  {
    id: "worship-4-5-3-6",
    name: "IV–V–iii–vi",
    aka: "Worship pre-chorus",
    genre: "Gospel / Worship",
    numerals: "IV–V–iii–vi",
    chords: [
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
      { o: 4, q: "Minor" },
      { o: 9, q: "Minor" },
    ],
  },

  // ── Classical / Cadences ─────────────────────────────
  {
    id: "classical-authentic",
    name: "Authentic Cadence",
    aka: "V–I",
    genre: "Classical",
    numerals: "V–I",
    chords: [
      { o: 7, q: "Major" },
      { o: 0, q: "Major" },
    ],
  },
  {
    id: "classical-plagal",
    name: "Plagal Cadence",
    aka: "Amen cadence IV–I",
    genre: "Classical",
    numerals: "IV–I",
    chords: [
      { o: 5, q: "Major" },
      { o: 0, q: "Major" },
    ],
  },
  {
    id: "classical-deceptive",
    name: "Deceptive Cadence",
    aka: "V–vi",
    genre: "Classical",
    numerals: "V–vi",
    chords: [
      { o: 7, q: "Major" },
      { o: 9, q: "Minor" },
    ],
  },
  {
    id: "classical-half",
    name: "Half Cadence",
    aka: "I–V or IV–V",
    genre: "Classical",
    numerals: "IV–V",
    chords: [
      { o: 5, q: "Major" },
      { o: 7, q: "Major" },
    ],
  },
  {
    id: "classical-circle",
    name: "Circle of Fifths (diatonic)",
    aka: "I–IV–viiø–iii–vi–ii–V–I",
    genre: "Classical",
    numerals: "I–IV–vii°–iii–vi–ii–V–I",
    chords: [
      { o: 0, q: "Major" },
      { o: 5, q: "Major" },
      { o: 11, q: "Diminished" },
      { o: 4, q: "Minor" },
      { o: 9, q: "Minor" },
      { o: 2, q: "Minor" },
      { o: 7, q: "Major" },
      { o: 0, q: "Major" },
    ],
  },
  {
    id: "classical-romanesca",
    name: "Romanesca",
    aka: "iii–VII–i–V / related",
    genre: "Classical",
    numerals: "I–V–vi–iii",
    chords: [
      { o: 0, q: "Major" },
      { o: 7, q: "Major" },
      { o: 9, q: "Minor" },
      { o: 4, q: "Minor" },
    ],
  },
];
